# Site settings
title: Science & Math blog
author: Andrew White
email: andrew@andrew-white.com
description: "A blog devoted to the glorious pursuit of mathsci."
baseurl: ""
url: "http://whitead.github.io/SM-Blog"
timezone: America/Chicago

#defaults. Empty for now

# Build settings
markdown: kramdown
permalink: pretty
gems: ['jekyll/scholar']

#Jekyll-scholar settings
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
